feat: use lint-staged for lint and fixes (#2258)
### 🎯 Goal

I got a bit frustrated with our pre-commit hook failing because changes
in files unrelated to the commit. Plus, the command ran by the
pre-commit hook was pretty slow, running for a couple of seconds.

It would be nice for the pre-commit hook to only lint the files that are
actually staged.

### 🛠 Implementation details

The easiest (and most standard) way to achieve that is by using the
`lint-staged` package. It allows to pass a list of **staged** files
(filtered by glob) to our lint commands.

That prevents the pre-commit hook from failing because of errors in
files that are not part of the commit. And, since we don't lint the
whole codebase every time, it runs faster too.

I also added a new command `fix-staged` that will run auto-fixes for the
staged files only. The pre-commit hook now prompts to use this command.

### Demo


https://github.com/GetStream/stream-chat-react/assets/975978/f36a7109-92e7-45a5-b431-1e99a8538285

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,9 +3,9 @@
 
 set -e
 
-if ! yarn run lint; then
-    yarn run lint-fix
-    echo "some files were not formatted correctly (prettier/eslint) commit aborted!"
-    echo "your changes are still staged, you can accept formatting changes with git add or ignore them by adding --no-verify to git commit"
+if ! yarn run lint-staged; then
+    echo
+    echo "Some files were not formatted correctly (see output above), commit aborted!"
+    echo "Consider running \"yarn run fix-staged\" to attempt auto-fix."
     exit 1
 fi
